# The URL the site will be built for
base_url = "https://grahamstevenson.me.uk"

# The site title and description; used in feeds by default.
title = "Compendium of Political Biographies"
author = "Graham Stevenson"
description = "Books, pamphlets, articles and speeches."

# The default language; used in feeds.
default_language = "en"

# We're not using sass, just plain idiomatic CSS
compile_sass = false

# Don't need to generate feeds or build a search index
generate_feeds = false
build_search_index = false

# We do want to generate a sitemap.xml file
generate_sitemap = true

taxonomies = [
    { name = "surname_initial", render = false },
    { name = "tags", render = false }
]

[extra]
