name: Build Zola website
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Build site with Zola
        shell: bash
        run: |
          set -euo pipefail
          image="ghcr.io/getzola/zola:v0.22.1"
          echo "Using image: $image"
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w "/workspace/" \
            "$image" build

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config

      - name: Copy built site to server
        run: |
          rsync -e ssh -qr public/ biogserver:/var/www/html
          echo "reading known_hosts"
          cat ~/.ssh/known_hosts
