name: Build Zola website
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1

      # - name: Build Zola + upload Pages artifact
      #   uses: getzola/github-pages@066755243e69f508fd1a74739fbf1a65f656c790
      #   with:
      #     zola_version: v0.22.0

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
          touch text.txt
          scp text.txt biogserver:test.txt

      # - name: Execute remote SSH commands
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.SERVER_IP_ADDRESS }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_DEPLOY_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       whoami
