name: Build Zola website
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1

      - name: Build site with Zola
        shell: bash
        run: |
          set -euo pipefail
          image="ghcr.io/getzola/zola:v0.22.1"
          echo "Using image: $image"
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w "/workspace/" \
            "$image" build

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
          touch text.txt
          ls
          ls /public
          scp /public biogserver:public

      # - name: Execute remote SSH commands
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.SERVER_IP_ADDRESS }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_DEPLOY_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       whoami
